---
- name: Create User promtail
  user:
    name: promtail
    create_home: no
    shell: /bin/false

- name: Download and unzip promtail
  ansible.builtin.unarchive:
    src: "https://github.com/grafana/loki/releases/download/{{ promtail_version }}/promtail-linux-{{'arm64' if ansible_architecture == 'aarch64' else 'amd64'}}.zip"
    dest: /var/tmp/
    remote_src: yes

- name: Copy files to the install locations
  copy:
    src: "/var/tmp/promtail-linux-{{'arm64' if ansible_architecture == 'aarch64' else 'amd64'}}"
    dest: /usr/local/bin
    remote_src: yes
    mode: a+x

# Allow the promtail user to read the /var/log directory
- name: Change Log file permissions
  command:
    cmd:  "setfacl -R -m u:promtail:rwX {{ item }}"
  loop:
  - "/var/log"
  - "/var/lib/docker/containers"
  - "/tmp"
  become: true

- name: Copy promtail config file
  template:
    src: templates/config-promtail.yml.j2
    dest: /usr/local/bin/config-promtail.yml

- name: Cleaning up the home directory source
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "promtail-linux-{{'arm64' if ansible_architecture == 'aarch64' else 'amd64'}}.zip"
  - "promtail-linux-{{'arm64' if ansible_architecture == 'aarch64' else 'amd64'}}"

- name: Copy systemd init file
  template:
    src: templates/promtail.service.j2
    dest:  /etc/systemd/system/promtail.service
    notify:
    - systemd reload

- name: Restart and enable the promtail service
  service:
    name: promtail
    state: restarted
    enabled: yes