---
# tasks file for promtail
- name: Deploy promtail service
  ansible.builtin.include_tasks: deploy.yml
  when: state|default('present') == 'present'

# - name: Uninstall promtail service
#   ansible.builtin.include_tasks: uninstall.yml
#   when: state|default('present') == 'absent'