---
- hosts: monitoring
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install required packages
      apt:
        pkg:
          - wget
          - tar
          - chrony
        state: latest
        update_cache: true
        # reload daemon-reload and start service go_app
    - name: Start chrony
      systemd:
        name: chrony
        state: started
        enabled: yes

- hosts: grafana
  remote_user: ubuntu
  become: true
  roles:
    - role: loki

- hosts: docker_servers
  remote_user: ubuntu
  become: true
  roles:
    - role: promtail
