---
- hosts: monitoring
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install required packages
      apt:
        pkg:
          - wget
          - tar
          - chrony
        state: latest
        update_cache: true
        # reload daemon-reload and start service go_app
    - name: Start chrony
      systemd:
        name: chrony
        state: started
        enabled: yes

- hosts: prometheus
  remote_user: ubuntu
  become: true
  vars:
    target_domain: deviot.ru
    target_port: 80
    exporter_ip: 192.168.15.4
  roles:
    - role: prometheus

- hosts: grafana
  remote_user: ubuntu
  become: true
  roles:
    - role: grafana

- hosts: [prometheus, docker_servers]
  remote_user: ubuntu
  become: true
  roles:
    - role: node_exporter
